### ISSUE TITLE
Error run build and dev +page.svelte

### ISSUE THREAD

**Issue by 94maldini** [Khaztaroth/Khaz-Tuna-OBS-widget#1]
I'm getting build and dev issues with the +page.svelte error problem.
```
vite v4.5.0 building SSR bundle for production...
✓ 54 modules transformed.
✓ built in 3.95s
[vite]: Rollup failed to resolve import "image-color-extraction/lib" from "E:/PluginStreming/Tuna-widget/Server/Folder Baru/Khaz-Tuna-OBS-widget-master/src/routes/+page.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "image-color-extraction/lib" from "E:/PluginStreming/Tuna-widget/Server/Folder Baru/Khaz-Tuna-OBS-widget-master/src/routes/+page.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///E:/PluginStreming/Tuna-widget/Server/Folder%20Baru/Khaz-Tuna-OBS-widget-master/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onRollupWarning (file:///E:/PluginStreming/Tuna-widget/Server/Folder%20Baru/Khaz-Tuna-OBS-widget-master/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48248:9)
    at onwarn (file:///E:/PluginStreming/Tuna-widget/Server/Folder%20Baru/Khaz-Tuna-OBS-widget-master/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at file:///E:/PluginStreming/Tuna-widget/Server/Folder%20Baru/Khaz-Tuna-OBS-widget-master/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///E:/PluginStreming/Tuna-widget/Server/Folder%20Baru/Khaz-Tuna-OBS-widget-master/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///E:/PluginStreming/Tuna-widget/Server/Folder%20Baru/Khaz-Tuna-OBS-widget-master/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///E:/PluginStreming/Tuna-widget/Server/Folder%20Baru/Khaz-Tuna-OBS-widget-master/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Khaztaroth** [comment]
Seems like a library that I planned on using but ended up not implementing because it was giving me issues. I forgot to remove the import from the project. 

I did also realize that using npm made the build really unhappy so I changed the instructions to just use yarn. 

Try the newest commit and see if that solves your issue.
